apps/posts/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('posts.views',
    url(r'^new/$', 'new', name='new'),
    url(r'^new/(?P<parent_id>\d+)/$', 'new', name='new_reply'),
    url(r'^edit/(?P<post_id>\d+)/$', 'edit', name='edit'),
    url(r'^view/(?P<post_id>\d+)/(?P<slug>[-\w]+)/$', 'view', name='view'),
    url(r'^recent-threads/$', 'list_recent_threads', name='list_recent_threads'),
)

apps/users/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('users.views',
    url(r'^login/$', 'login', name='login'),
    url(r'^logout/$', 'logout', name='logout'),
    url(r'^register/$', 'register', name='register'),
    url(r'^edit_profile/$', 'edit_profile', name='edit_profile'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('home.urls', namespace='home')),   
    url(r'^users/', include('users.urls', namespace='users')),   
    url(r'^posts/', include('posts.urls', namespace='posts')),   
    url(r'^tags/', include('tags.urls', namespace='tags')),   
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sentry/', include('sentry.web.urls')),
    (r'^tinymce/', include('tinymce.urls')),
)
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
    )

templates/default/base-gdi.html
{% spaceless %}
{% load url from future %}
{% load compress %}

<!DOCTYPE html>
<html>
    <head>
    {# Web Fonts Impot #}
    <link href='http://fonts.googleapis.com/css?family=Play:700&v2' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Varela&v2' rel='stylesheet' type='text/css'>
    
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js" type="text/javascript" charset="utf-8"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="{{ STATIC_URL}}js/jquery.layout.min-1.2.0.js" type="text/javascript"></script>
    {# Global CSS Files #}
    <link type="text/css" href="{{ STATIC_URL }}css/default/main.css" rel="Stylesheet" />
    <link type="text/css" href="{{ STATIC_URL }}css/default/chosen.css" rel="Stylesheet" />
    <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/dot-luv/jquery-ui.css">

    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/default/tagit/jquery.tagit.css">
    <title>
	{% block headername %}
		Gamedevid v2
	{% endblock %}
	</title>
    
    {% block css-local %}{% endblock %}
    
    </head>
    <body>
        <div id="global_container">
            <div id='header'>
				<!--
                <a href='/' id="header_text">GameDevID</a>
                <a href='/' id="header_info">Indonesia Game Developers</a>
				-->
				<a class="logo" href='/'><img src="http://www.gamedevid.org/forum/styles/GDIDark/misc/hdr_logo-o.gif"/></a>
				
				<div style="display:inline-block; vertical-align:top; margin:20px; margin-left:560px;">
					{% include "users/login_widget.html" %}
				</div>
				
            </div>
            
			{% include "users/inline_navbar.html" %}
			
            <div id='content'>
                <table width='100%'>
                    <tbody>
                        <tr>
                            <td style='vertical-align:top'>
                                {% block content %}{% endblock %}
                            </td>
                            <td style='width:280px;vertical-align:top'>
                                {% include "sidebar.html" %}
                            </td>
                        </tr>
                    </tbody>
                </table>
                
            </div>
            <div id='footer'>
                <p align='center'>
                    <small>Gamedevid 2011</small>
                </p>
            </div>
        </div>
       
        

        

        {% block js-local %}{% endblock %}
        {# Global JS Files #}
        <script src="/static/js/tag-it.js" type="text/javascript" charset="utf-8"></script>
        <script src="/static/js/chosen.jquery.js"></script>

        <script>
        $(document).ready(function(){
            /*
            mainLayout = $('body').layout({
                applyDefaultStyles:true,
                initClosed:true,

            });
            */
            $('.ui-layout-south').css('padding','0px');
            $('body').css('overflow', 'scroll');
        });
        </script>
    </body>
</html>
{% endspaceless %}

templates/default/base.html
{% spaceless %}
{% load url from future %}
{% load compress %}

<!DOCTYPE html>
<html>
    <head>
    {# Web Fonts Impot #}
    <link href='http://fonts.googleapis.com/css?family=Play:700&v2' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Varela&v2' rel='stylesheet' type='text/css'>
    
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js" type="text/javascript" charset="utf-8"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="{{ STATIC_URL}}js/jquery.layout.min-1.2.0.js" type="text/javascript"></script>
    {# Global CSS Files #}
    <link type="text/css" href="{{ STATIC_URL }}css/default/main.css" rel="Stylesheet" />
    <link type="text/css" href="{{ STATIC_URL }}css/default/chosen.css" rel="Stylesheet" />
    <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/dot-luv/jquery-ui.css">

    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/default/tagit/jquery.tagit.css">
    <title>Gamedevid v2</title>
    
    {% block css-local %}{% endblock %}
    
    </head>
    <body>
        <div id="global_container">
            <div id='header'>
				<!--
                <a href='/' id="header_text">GameDevID</a>
                <a href='/' id="header_info">Indonesia Game Developers</a>
				-->
				<a class="logo" href='/'><img src="http://www.gamedevid.org/forum/styles/GDIDark/misc/hdr_logo-o.gif"/></a>
            </div>
            
            <div id='content'>
                <table width='100%'>
                    <tbody>
                        <tr>
                            <td style='vertical-align:top'>
                                {% block content %}{% endblock %}
                            </td>
                            <td style='width:280px;vertical-align:top'>
                                {% include "sidebar.html" %}
                            </td>
                        </tr>
                    </tbody>
                </table>
                
            </div>
            <div id='footer'>
                <p align='center'>
                    <small>Gamedevid 2011</small>
                </p>
            </div>
        </div>
       
        

        

        {% block js-local %}{% endblock %}
        {# Global JS Files #}
        <script src="/static/js/tag-it.js" type="text/javascript" charset="utf-8"></script>
        <script src="/static/js/chosen.jquery.js"></script>

        <script>
        $(document).ready(function(){
            /*
            mainLayout = $('body').layout({
                applyDefaultStyles:true,
                initClosed:true,

            });
            */
            $('.ui-layout-south').css('padding','0px');
            $('body').css('overflow', 'scroll');
        });
        </script>
    </body>
</html>
{% endspaceless %}

templates/default/sidebar-with-navbar.html
{% load url from future %}
{% include "users/auth_widget.html" %}
{% if request.user.is_authenticated %}
<div class='column'>
    <div class='column_header'>Hello, {{request.user}}</div>
		<div class="user_action"><a href='/'>Home</a></div>
        <div class="user_action"><a href="javascript:mainLayout.toggle('south')">Chat</a></div>
        <div class="user_action"><a href='{% url "posts:new" %}'>Write Post</a></div>
        <div class="user_action"><a href='{% url "posts:new" %}?game=yes'>Submit Game</a></div>
        <div class="user_action"><a href='{% url "posts:new" %}?image=yes'>Submit Image</a></div>
        <br /><br />
        <div class="user_action"><a href='{% url "users:edit_profile" %}'>Edit Profile</a></div>
        <div class="user_action"><a href='{% url "users:logout" %}'>Log Out</a></div>
    </div>
</div>


{% endif %}

<div class='column'>
<div class='column_header'>Forums</div>
{% include "tags/brief_list.html" %}
</div>
<div class='column'>
    <div class='column_header'>Recent Threads <a class="small_link" href='{% url "posts:list_recent_threads" %}'>(View All)</a> </div>
    {% for p in global_latest_posts %}
		<div class="{% cycle 'recent_threads_item_box_even' 'rect_threads_item_box_odd' %}">
        <a class="recent_threads_item" href='{% url "posts:view" post_id=p.id slug=p.title_slug %}'>
			{% if not request.user in p.get_readers %}
			<span class="recent_threads_item_unread">
			{% endif %}
			{{p.title|truncatewords:5}}
			{% if not request.user in p.get_readers %}
			</span>
			{% endif %}
			<span class='info'>({{p.get_replies.count}}) {{p.get_last_reply.author}}</span>
        </a>
		</div>
    {% endfor %}
</div>

templates/default/sidebar.html
{% load url from future %}
{% include "users/auth_widget.html" %}
{% if request.user.is_authenticated %}
<div class='column'>
    <div class='column_header'>Hello, {{request.user}}</div>
		<div class="user_action"><a href='/'>Home</a></div>
        <div class="user_action"><a href="javascript:mainLayout.toggle('south')">Chat</a></div>
        <div class="user_action"><a href='{% url "posts:new" %}'>Write Post</a></div>
        <div class="user_action"><a href='{% url "posts:new" %}?game=yes'>Submit Game</a></div>
        <div class="user_action"><a href='{% url "posts:new" %}?image=yes'>Submit Image</a></div>
        <br /><br />
        <div class="user_action"><a href='{% url "users:edit_profile" %}'>Edit Profile</a></div>
        <div class="user_action"><a href='{% url "users:logout" %}'>Log Out</a></div>
    </div>
</div>


{% endif %}

<div class='column'>
<div class='column_header'>Forums</div>
{% include "tags/brief_list.html" %}
</div>
<div class='column'>
    <div class='column_header'>Recent Thread (<a href='{% url "posts:list_recent_threads" %}'>View All</a>) </div>
    {% for p in global_latest_posts %}
		<div class="{% cycle 'recent_threads_item_box_even' 'rect_threads_item_box_odd' %}">
        <a class="recent_threads_item" href='{% url "posts:view" post_id=p.id slug=p.title_slug %}'>
			{% if not request.user in p.get_readers %}
			<span class="recent_threads_item_unread">
			{% endif %}
			{{p.title|truncatewords:5}}
			{% if not request.user in p.get_readers %}
			</span>
			{% endif %}
			<span class='info'>({{p.get_replies.count}}) {{p.get_last_reply.author}}</span>
        </a>
		</div>
    {% endfor %}
</div>