apps/posts/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('posts.views',
    url(r'^new/$', 'new', name='new'),
    url(r'^new/(?P<parent_id>\d+)/$', 'new', name='new_reply'),
    url(r'^edit/(?P<post_id>\d+)/$', 'edit', name='edit'),
    url(r'^view/(?P<post_id>\d+)/(?P<slug>[-\w]+)/$', 'view', name='view'),
    url(r'^recent-threads/$', 'list_recent_threads', name='list_recent_threads'),
)

apps/tags/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('tags.views',
    url(r'^(?P<tag_id>\d+)/(?P<slug>[-\w]+)/$', 'tag_post_list', name='tag_post_list'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('home.urls', namespace='home')),   
    url(r'^users/', include('users.urls', namespace='users')),   
    url(r'^posts/', include('posts.urls', namespace='posts')),   
    url(r'^tags/', include('tags.urls', namespace='tags')),   
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sentry/', include('sentry.web.urls')),
    (r'^tinymce/', include('tinymce.urls')),
)
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
    )

apps/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template import defaultfilters

# Create your models here.
class Post(models.Model):
    title = models.TextField(blank = True)
    content = models.TextField(blank = False)
    author = models.ForeignKey(User, related_name = "post")
    date_created = models.DateTimeField(auto_now_add = True)
    parent = models.ForeignKey("self", null = True)
    date_sorted = models.DateTimeField(blank = True, null = True, auto_now_add = True) #Filled only for parent thread, for sorting purpose (need improvement later)
    def __unicode__(self):
        if self.title:
            return self.title
        return u'' #For legacy support since last time we still have null-able titles
        
    @property
    def content_short(self):
        if len(self.content) < 255:
            return self.content
        return self.content[:255] + "..."
    @property
    def title_short(self):
        if len(self.title) < 20:
            return self.title
        return self.title[:20] + "..."
    @property
    def sticky_tags(self):
        return self.tags.filter(tag__sticky = True)
    @property
    def optional_tags(self):
        tags = []
        for t in self.tags.all().order_by('-id'):
            if not t.tag.sticky:
                tags.append(t.tag)
        return tags if len(tags) > 0 else None
    @staticmethod
    def get_latests():
        return Post.objects.filter(parent = None).order_by('-date_sorted')
    def get_replies(self):
        return Post.objects.filter(parent = self).order_by('id')
    def get_last_reply(self):
        return self.get_replies().all().order_by('-id').latest('id')
    def title_slug(self):
        return defaultfilters.slugify(self.title)
    def get_readers(self):
        return [r.user for r in self.reader.all()]
    class Meta:
        db_table = u'post'


"""
Ability to show unread posts to some particular users.

Everytime a new posts/reply has been made, we remove all entry of that post in this table
That simply means, nobody has read it. When a particular user open that post, we added
that user along with the post that he opened, that means that user has read it. When
another user makes a reply in that post, remove entry of that post again.

We only store the parent of the post. that means, reply will not be stored, instead, it's
parent will be stored.
"""

class PostReader(models.Model):
    user = models.ForeignKey(User, related_name = 'reader')
    post = models.ForeignKey(Post, related_name = 'reader')
    date_created = models.DateTimeField(auto_now_add = True)
    @staticmethod
    def clear(post):
        readers = PostReader.objects.filter(post = post)
        for r in readers:
            r.delete()
    @staticmethod
    def add(user, post):
        try:
            reader = PostReader.objects.get(user = user, post = post)
        except PostReader.DoesNotExist:
            reader = PostReader(user = user, post = post)
            reader.save()
        return reader
    class Meta:
        db_table = u'post_reader'

apps/posts/forms.py
from django import forms
from django.forms import ValidationError
from datetime import datetime 
from django.contrib.auth.models import User
from tinymce.widgets import TinyMCE
from models import Post

class PostForm(forms.ModelForm):
    title = forms.CharField(required = True)
    def __init__(self, *args, **kwargs):
        self.author = kwargs.pop('author')
        parent = None
        quick_reply = False
        if 'parent' in kwargs:
            parent = kwargs.pop('parent')
        if 'quick_reply' in kwargs:
            quick_reply = kwargs.pop('quick_reply')

        super(PostForm, self).__init__(*args, **kwargs)
        
        is_reply = False
        if self.instance.pk:
            if self.instance.parent:
                is_reply = True
        if parent: #If it's in reply mode, don't use title
            is_reply = True
            self.instance.parent = parent
        
        if is_reply:
            self.fields.pop('title')

        content_cols = 80
        content_rows = 20
        if quick_reply:
            content_cols = 50
            content_rows = 10
        
        self.fields['content'] = forms.CharField(widget=TinyMCE(attrs={'cols':content_cols, 'rows':content_rows}))
    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) < 8:
            raise ValidationError("Your title is too short!")
        try:
            if self.instance.pk:
                return title
        except:
            pass
        try:
            post = Post.objects.get(title = title)
            if post is not None:
                raise ValidationError("This title already exists")
        except Post.DoesNotExist:
            return title
    def clean_content(self):
        content = self.cleaned_data['content']
        if len(content) < 30:
            raise ValidationError("Your post is too short!")
        try:
            if self.instance.pk:
                return content
        except:
            pass
        try:
            post = Post.objects.get(content = content)
            if post is not None:
                raise ValidationError("This content already exists")
        except Post.DoesNotExist:
            return content
    def is_valid(self):
        is_valid = super(PostForm, self).is_valid()
        try:
            if self.instance:
                if is_valid:
                    if self.instance.author == self.author or self.author.is_superuser or self.author.is_staff:
                        return True
                    else:
                        return False
        except:
            pass
        return is_valid
    def save(self):
        if not self.instance.pk: #it's a new post/reply
            self.instance.author = self.author
            if self.instance.parent is None:
                self.instance.date_sorted = datetime.now()
            else:
                self.instance.parent.date_sorted = datetime.now()
                self.instance.parent.save()
        return super(PostForm, self).save(commit = True)
        
    class Meta:
        model = Post
        exclude = ('author','parent')

apps/posts/views.py
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.shortcuts import redirect
from django.core.files.base import ContentFile
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from .models import Post, PostReader
from images.forms import ImageForm
from games.forms import GameForm
from .forms import PostForm
from tags.forms import TagForm

from django.core.paginator import Paginator, InvalidPage, EmptyPage

def list_recent_threads(request):
    posts = Post.get_latests()

    paginator = Paginator(posts, 40)
    try:
        page = int(request.GET.get('page','1'))
        posts = paginator.page(page)
    except ValueError:
        page = 1
    try:
        posts = paginator.page(page)
    except (EmptyPage, InvalidPage):
        posts = paginator.page(paginator.num_pages)
    context = {
        'post_list' : posts,
    }
    return render_to_response(
        'posts/recent_threads.html',
        context,
        RequestContext(request)
    )
        


@login_required
def new(request, parent_id = None):
    parent = None
    save_mode = None
    if parent_id:
        parent = get_object_or_404(Post, pk = parent_id)
    form = PostForm(
        request.POST or None,
        request.FILES or None,
        author = request.user, 
        parent = parent,
    )
    
    image_form = ImageForm(request.POST or None, request.FILES or None)
    game_form = GameForm(request.POST or None, request.FILES or None)

    tag_form = TagForm(request.POST or None) if parent is None else None

    valid = False
    
    #A reply
    if parent is not None:
        valid = (parent is not None and form.is_valid())
    
    #a new post:
    if parent is None:
        valid = (parent is None and form.is_valid() and tag_form.is_valid())
    
    #an image post:
    if request.GET.get('image',False):
        save_mode = 'image'
        valid = (parent is None and form.is_valid() and tag_form.is_valid() and image_form.is_valid())

    #a game post:
    if request.GET.get('game',False):
        save_mode = 'game'
        valid = (parent is None and form.is_valid() and tag_form.is_valid() and game_form.is_valid())

    if valid:       
        post = form.save()
        if parent is None:
            tag_form.post = post
            tag_form.save()
        
        if parent is None:
            PostReader.clear(post = post)
        else:
            PostReader.clear(post = post.parent)
        
        if image_form.is_valid() and save_mode == 'image':
            image_form.save(post = post)
        
        if game_form.is_valid() and save_mode == 'game':
            game_form.save(post = post)
            game_form.save_m2m()

        r_post = post if not parent else parent
        return redirect(reverse("posts:view", args=[r_post.id, r_post.title_slug()])) 
    context = {
                'form' : form,
                'tag_form' : tag_form,
                'image_form' : image_form,
                'game_form' : game_form,
              }

    return render_to_response(
                                "posts/post_form.html",
                                context,
                                RequestContext(request)
                             )
@login_required
def edit(request, post_id):
    post = get_object_or_404(Post, pk = post_id)
    parent = post.parent
    form = PostForm(request.POST or None, instance = post, author = request.user)
    tag_form = TagForm(request.POST or None, post = post) if parent is None else None
    if (parent is not None and form.is_valid()) or (parent is None and form.is_valid() and tag_form.is_valid()):
        form.save()
        if parent is None:
            tag_form.save()
        r_post = post if not post.parent else post.parent
        return redirect(reverse("posts:view", args=[r_post.id, r_post.title_slug()])) 
    context = {
                'form' : form,
                'tag_form' : tag_form,
              }

    return render_to_response(
                                "posts/post_form.html",
                                context,
                                RequestContext(request)
                             )

def view(request, post_id, slug):
    post = get_object_or_404(Post, pk = post_id)
    post_parent = post
    posts = Post.objects.filter(Q(pk = post_id) | Q(parent = post)).order_by('id') 
    paginator = Paginator(posts, 10)
    try:
        page = int(request.GET.get('page',paginator.num_pages))
        posts = paginator.page(page)
    except ValueError:
        page = paginator.num_pages
    try:
        posts = paginator.page(page)
    except (EmptyPage, InvalidPage):
        posts = paginator.page(paginator.num_pages)

    reply_form = PostForm(author = request.user, quick_reply = True) # No need to get anything here, coz it'll be redirected to reply page

    if request.user.is_authenticated():
        PostReader.add(user = request.user, post = post if post.parent is not None else post)

    context = {
                'posts' : posts,
                'post_parent' : post_parent,
                'reply_form' : reply_form,
              }

    return render_to_response(
                                "posts/view_main.html",
                                context,
                                RequestContext(request)
                             )

templates/default/posts/header_widget.html
{% load url from future %}
{% if request.user.is_authenticated %}
{% endif %}

templates/default/posts/post_form.html
{% extends "base.html" %}
{% load url from future %}

{% block headername %}
	{% if request.GET.image %}
		Submit Image [Gamedevid v2]
	{% else %} {% if request.GET.game %}
		Submit Game [Gamedevid v2]
	{% else %}
		Write Post [Gamedevid v2]
	{% endif %} {% endif %}
{% endblock %}

{% block content %}
{{form.media}}
<script>
$(function(){
    var sampleTags = [
        {% for t in tag_form.tag_optional_list %}
            '{{t}}',
        {% endfor %}
    ];
    $("#id_title").attr('class','ui-text');
    $("#id_tag_sticky").attr('style','width:250px'); 
    $("#id_tag_sticky").chosen(); 
    $("#id_tag_optional").tagit({
        availableTags: sampleTags,
    });
});
</script>

<form method='post' action='' class='ui-form' enctype='multipart/form-data'>
{{form.errors}}
{{tag_form.errors}}
{% if request.GET.image %}{{image_form.errors}}{% endif %}
{% if request.GET.game %}{{game_form.errors}}{% endif %}
{% if request.GET.image %}
    <h2>Submit Image</h2>
    You can submit your Work In Progress (WIP) Game, Game Art, or anything related to game development in here. If this is a finished game, please use "Submit a Game" instead.
    <input type='hidden' name='tag_sticky' value='{{SETTINGS.TAG_IMAGE_ID}}' />
{% endif %}

{% if request.GET.game %}
    <h2>Submit Game</h2>
    Submit your finalized game here. Don't forget to include your game screenshot, download links (if any), developer name, release date, genre and platform.
    <input type='hidden' name='tag_sticky' value='{{SETTINGS.TAG_GAME_ID}}' />
{% endif %}


{% if form.title %}
    <table>
        <tbody>
            <tr>
            {% if not request.GET.image and not request.GET.game%}
                <td width='200'>{{tag_form.tag_sticky}}</td>
            {% endif %}
            
            <td>{{form.title}}</td>
            
            {% if request.GET.image and not request.GET.game %}
            <tr>
                <td style='color:#ffffff'>{{image_form.image}}</td>
            </tr>
            {% endif %}
            {% if request.GET.game and not request.GET.image %} 
            <tr>
                <td>
                    <table width='100%' cellspacing='0' cellpadding='0'>
                        <tbody>
                            <tr><th>Screenshot (Required)</th><td>{{game_form.image}}</td></tr>
                            <tr><th>Developer</th><td>{{game_form.developer}}</td></tr>
                            <tr><th>Release Date</th><td>{{game_form.release_date}}</td></tr>
                            <tr><th>Genre</th><td>{{game_form.genre}}</td></tr>
                            <tr><th>Platform</th><td>{{game_form.platform}}</td></tr>
                            <tr><th>Download URL</th><td>{{game_form.download_url}}</td></tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            
            {% endif %}
            </tr>
        </tbody>
    </table>
{% endif %}
{{form.content}}<br />
{% if tag_form.tag_optional %}
Optional Tags: {{tag_form.tag_optional}}<br />
{% endif %}
{% csrf_token %}
<button type='submit'>Post</button>
</form>

{% endblock %}

templates/default/posts/post_latest.html
{% load url from future %}

<table width='100%'>
<thead>
    <tr>
        <th align='left'>Post</th>
        <th>Forum</th>
        <th>Replies</th>
        <th>Last Replied</th>
    </tr>
</thead>
<tbody>
{% for p in posts_latests %}
    <tr>
        <td width='50%'>
            {% if not request.user in p.get_readers %}
            <b>
            {% endif %}
            <a href='{% url "posts:view" post_id=p.id slug=p.title_slug %}'>{{p.title}}</a>
            {% if not request.user in p.get_readers %}
            </b>
            {% endif %}<br />
            by {{p.author}}
        </td>
        <td align='center' width='25%'>
            {% if p.tags %}
            {% if p.sticky_tags %}
                {% for t in p.sticky_tags %}
                    <span class='post_tag_item_sticky'>{{t.tag}}</span>
                {% endfor %}
            {% endif %}
            {% endif %}
        </td>
        <td align='center'>{{p.get_replies.count}}</td>
        <td>
            {% if p.get_replies.count > 0 %}
                {{p.get_last_reply.author}} on {{p.get_last_reply.date_created}}
            {% endif %}

        </td>
    </tr>
{% endfor %}
</tbody>

</table>

templates/default/posts/post_list.html
{% load url from future %}

<div class='column'>
<div class='column_header'>Search Anu</div>

<table width='100%'>
<thead>
    <tr>
        <th style="text-align:center; font-size:12px; font-weight:bold;">Thread</th>
        <th style="text-align:center; font-size:12px; font-weight:bold;">Forum</th>
        <th style="text-align:center; font-size:12px; font-weight:bold;">Replies</th>
		<th style="text-align:center; font-size:12px; font-weight:bold;">Views</th>
        <th style="text-align:center; font-size:12px; font-weight:bold;">Last Replied</th>
    </tr>
</thead>

<tbody>
{% for p in post_list.object_list %}
    <tr class="{% cycle 'recent_threads_item_box_even' 'rect_threads_item_box_odd' %}">
        <td width='50%'>
            {% if not request.user in p.get_readers %}
            <b>
            {% endif %}
            <a href='{% url "posts:view" post_id=p.id slug=p.title_slug %}'>{{p.title}}</a>
            {% if not request.user in p.get_readers %}
            </b>
            {% endif %}<br />
            by {{p.author}}
        </td>
        <td style="text-align:center" width='25%'>
            {% if p.tags %}
            {% if p.sticky_tags %}
                {% for t in p.sticky_tags %}
                    <a href='{% url 'tags:tag_post_list' tag_id=t.tag.id slug=t.tag.slug %}' class='post_tag_item_sticky'>{{t.tag}}</a>
                {% endfor %}
            {% endif %}
            {% endif %}
        </td>
        <td style="text-align:center">{{p.get_replies.count}}</td>
		<td style="text-align:center"></td>
        <td style="text-align:center">
            {% if p.get_replies.count > 0 %}
				<div style='font-size:12px;color:#f1b906;'>
                {{p.get_last_reply.date_created}}
				</div>
				<small>by {{p.get_last_reply.author}}</small>
            {% endif %}

        </td>
    </tr>
{% endfor %}
</tbody>


</table>
<br /><br />
Jump to: 
{% for n in post_list.paginator.page_range %}
    {% if n == post_list.number %}
        <b>{{n}}</b>
    {% else %}
        <a href='?page={{n}}'>{{n}}</a>
    {% endif %}&nbsp;
{% endfor %}

</div>

templates/default/posts/posts_paging.html
{% load url from future %}
Page : 
{% for n in posts.paginator.page_range %}
    {% if n == posts.number %}
        <b>{{n}}</b>
    {% else %}
        <a href='?page={{n}}'>{{n}}</a>
    {% endif %}&nbsp;
{% endfor %}

templates/default/posts/quick_reply_form.html
{% load url from future %}


{{reply_form.media}}

<form method='post' action='{% url "posts:new_reply" parent_id=post.id %}'>
<div align='center'>{{reply_form.content}}</div><br />
{% csrf_token %}
<button type='submit'>Reply</button>&nbsp;&nbsp;
<button type='reset'>Reset</button>
</form>

templates/default/posts/recent_threads.html
{% extends "base.html" %}

{% block headername %}
Recent Threads [Gamedevid v2]
{% endblock %}

{% block content %}
{% include "posts/post_list.html" with post_list=post_list %}
{% endblock %}

templates/default/posts/view_entry.html
{% load url from future %}
{% load thumbnail %}
<tr>
    <td width='150px' align='center' valign='top' style='background-color:#333333'>
        <div class='post_author'>
        <a class='author_nickname'>{{p.author}}</a><br /><br />

        <img src='{% thumbnail p.author.avatar.image 128x128 %}' class='avatar' /><br />

        Last Login: {{p.author.last_login|date:"y/m/d"}} <br />
        Join Date: {{p.author.date_joined|date:"y/m/d"}} <br />
        Posts : {{p.author.post.count}} <br />
        </div>
    </td>
    <td valign='top' style='background-color:#3f3f3f'>
        <div class='post_header'>
            {% if request.user == p.author or request.user.is_staff or request.user.is_superuser %}
	    <span class="user_action"><a href='{% url 'posts:edit' post_id=p.id %}'>Edit</a></span> 
	    {% else %}
	    &nbsp;
	    {% endif %}
            <div style='float:right;font-size:10px;padding-right:10px;'>
                {{p.date_created}}
            </div>
        </div>
        {% if p.sticky_tags.all.0.tag.id == SETTINGS.TAG_IMAGE_ID %}
        <div class='random_image_container'>
            <img src='{% thumbnail p.image.image 550x413 %}' />
        </div>
        {% endif %}
        <div class='post_content'>
        {% if p.sticky_tags.all.0.tag.id == SETTINGS.TAG_GAME_ID %}
        <div class='random_image_container'>
        <table width='100%'>
            <tbody>
                <tr>
                    <td style='width:300px; border:none;'>
                        <img src='{% thumbnail p.game.image 550x413 %}' />
                    </td>
                    <td align='left' valign='top' style='border:none'>
                        Developer : {{p.game.developer}} <br />   
                        Platform : {{p.game.platform_join}}    <br />
                        Genre : {{p.game.genre_join}}    <br />
                        {% if p.game.download_url %}<br />
                        Download : <a href='p.game.download_url'>{{p.game.download_url}}</a>    
                        {% endif %}
                    </td>
                </tr>
            </tbody>
        </table>
        </div>
        {% endif %}
        
        
        {{p.content|removetags:SETTINGS.POST_CONTENT_UNALLOWED_TAGS|safe}}
        {# allow edit for both author and admin #}
        {% if p.author == request.user or request.user.is_staff or request.user.is_superuser %}
        {% endif %}
        </div>
    </td>
</tr>

templates/default/posts/view_main.html
{% extends "base.html" %}
{% load url from future %}

{% block headername %}
{{post_parent.title}} [Gamedevid v2]
{% endblock %}

{% block content %}

{% include "tags/breadcrumbs.html" with post=post_parent %}
{% include "posts/posts_paging.html" with posts=posts %}
<div class='post_title'>
    {{post_parent.title}}
    {% with post_parent as p %}
    {% if p.tags %}
        <div class='post_tag'>
        {% if p.sticky_tags %}
            {% for t in p.sticky_tags %}
                <a href='{% url 'tags:tag_post_list' tag_id=t.tag.id slug=t.tag.slug %}' class='post_tag_item_sticky'>{{t.tag}}</a>
            {% endfor %}
        {% endif %}
       
        {% for t in p.optional_tags %}
            <a href='{% url 'tags:tag_post_list' tag_id=t.id slug=t.slug %}' class='post_tag_item'>{{t}}</a>
        {% endfor %}
        </div>
    {% endif %}
    {% endwith %}
</div>

<table class='thread_posts' cellspacing='0' cellpadding='0'>
<tbody>
{% for p in posts.object_list %}
    {% include "posts/view_entry.html" with p=p %}
{% endfor %}
</tbody>
</table>
{% include "posts/posts_paging.html" with posts=posts %}
<div class='quick_reply_container' align='center'>
    {% include "posts/quick_reply_form.html" with post=post_parent %}
</div>
{% include "tags/breadcrumbs.html" with post=post_parent %}

{% endblock %}