apps/posts/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('posts.views',
    url(r'^new/$', 'new', name='new'),
    url(r'^new/(?P<parent_id>\d+)/$', 'new', name='new_reply'),
    url(r'^edit/(?P<post_id>\d+)/$', 'edit', name='edit'),
    url(r'^view/(?P<post_id>\d+)/(?P<slug>[-\w]+)/$', 'view', name='view'),
    url(r'^recent-threads/$', 'list_recent_threads', name='list_recent_threads'),
)

apps/users/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('users.views',
    url(r'^login/$', 'login', name='login'),
    url(r'^logout/$', 'logout', name='logout'),
    url(r'^register/$', 'register', name='register'),
    url(r'^edit_profile/$', 'edit_profile', name='edit_profile'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('home.urls', namespace='home')),   
    url(r'^users/', include('users.urls', namespace='users')),   
    url(r'^posts/', include('posts.urls', namespace='posts')),   
    url(r'^tags/', include('tags.urls', namespace='tags')),   
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sentry/', include('sentry.web.urls')),
    (r'^tinymce/', include('tinymce.urls')),
)
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
    )

apps/legacies/users/models.py
from django.db import models
import md5
class User(models.Model):
    id = models.IntegerField(primary_key=True)
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=32)
    salt =  models.CharField(max_length=3)
    
    @staticmethod
    def authenticate(username, password):
        user = None
        try:
            user = User.objects.get(username = username)
            if user:
                password = md5.new(password).hexdigest()
                password = md5.new(password + user.salt).hexdigest()
                if password == user.password:
                    return user
                else:
                    return None
        except User.DoesNotExist:
            return None

        return user

    class Meta:
        db_table = 'old_user'

apps/users/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())
    def clean(self, *args, **kwargs):
        if self.errors:
            return
        username = self.data['username']
        password = self.data['password']
        self.user = auth.authenticate(username=username, password=password)
        if username and password:
            if self.user is not None:
                if not self.user.is_active:
                    raise forms.ValidationError("Inactive user.")
            else:
                raise forms.ValidationError("Bad username or password.")
        return self.data
    def save(self, *args, **kwargs):
        return self.user

class RegisterForm(forms.Form):
    username = forms.CharField(required = True)
    email = forms.EmailField(required = True)
    password = forms.CharField(widget = forms.PasswordInput(), required = True)
    confirm_password = forms.CharField(widget = forms.PasswordInput(), required = True)
    def clean_confirm_password(self):
        password = self.data['password']
        confirm_password = self.data['confirm_password']
        if not password == confirm_password:
            raise forms.ValidationError("Password mismatched")
        return password
    def clean_username(self):
        username = self.data['username']
        try:
            user = User.objects.get(username = username)
            if user is not None:
                raise forms.ValidationError("Username already exists")
        except User.DoesNotExist:
            return username
    def save(self, *args, **kwargs):
        username = self.data['username']
        password = self.data['password']
        email = self.data['email']
        user = User.objects.create_user(username = username, email = email, password = password)
        user.is_active = True
        user.save()
        user = auth.authenticate(username = username, password = password)
        return user

apps/users/views.py
from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as logout_user
from .forms import LoginForm, RegisterForm
from avatars.forms import AvatarForm
def login(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        next_url = request.GET.get('next', "/")
        user = form.save()
        auth.login(request, user)
        return redirect(next_url)
    context = {
                'form' : form,
              }

    return render_to_response(
                                "users/login.html",
                                context,
                                RequestContext(request)
                             )
@login_required
def edit_profile(request):
    avatar_form = AvatarForm(request.POST or None, request.FILES or None)
    #for now this is okay, if later on we have multiple form, we'll need to update this
    if avatar_form.is_valid():
        avatar_form.save(user = request.user)
        next_url = request.GET.get('next', reverse('users:edit_profile'))
        return redirect(next_url)
    context = {
                'avatar_form' : avatar_form,
              }

    return render_to_response(
                                "users/edit_profile.html",
                                context,
                                RequestContext(request)
                             )

    

@login_required
def logout(request):
    logout_user(request)
    next_url = request.GET.get('next', "/")
    return redirect(next_url)
def register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        next_url = request.GET.get('next', "/")
        user = form.save()
        auth.login(request, user)
        return redirect(next_url)
    context = {
                'form' : form,
              }

    return render_to_response(
                                "users/register.html",
                                context,
                                RequestContext(request)
                             )

templates/default/users/auth_widget.html
{% load url from future %}
{% if request.user.is_authenticated %}
{% else %}
<!--<div id='header_bottom'></div>-->

<!--
<span class="user_action">
<a href='{% url "users:register" %}'>Register</a>
</span>
<span class="user_action">
<a href='{% url "users:login" %}'>Login</a>
</span>
<div id='nav'>
<form method='post' action='{% url "users:login" %}'>
	<small>Please login with your old GDI account if you have one</small><br/>
    <input type='text' name='username' id='username' /> 
    <input type='password' name='password' id='password' />
    <button type='submit'>Login</button>
    {% csrf_token %}
</form>
</div>
-->

<div class='column'>
    <div class='column_header'>Hello, {{request.user}}</div>
		<div class="user_action"><a href='/'>Home</a></div>
        <div class="user_action"><a href='{% url "users:register" %}'>Register</a></div>
        <div class="user_action"><a href='{% url "users:login" %}'>Login</a></div>
		<br/>
        <div id='nav'>
		<form method='post' action='{% url "users:login" %}'>
			<div style="float:left;">
			<small>username</small>
			<br/>
			<input type='text' name='username' id='username' />
			</div>
			<div style="float:left;">
			<small>password</small>
			<br/>
			<input type='password' name='password' id='password' />
			</div>
			<div style="float:left;">
			<button type='submit'>Login</button>
			</div>
			<small>Please login with your old GDI account if you have one</small><br/>
			{% csrf_token %}
		</form>
		</div>
    </div>
</div>

{% endif %}

templates/default/users/edit_profile.html
{% extends "base.html" %}
{% load url from future %}
{% load thumbnail %}
{% block content %}


<h2>Edit Profile</h2>
{{avatar_form.errors}}
<form method='post' action='' class='ui-form' enctype='multipart/form-data'>

Current Avatar : <img src='{% thumbnail request.user.avatar.image 128x128 %}' class='avatar' /> <br />
Upload Avatar : {{avatar_form.image}}
{% csrf_token %}

<br /><br />
<button type='submit'>Save</button>
</form>

{% endblock %}

templates/default/users/inline_navbar.html
{% load url from future %}

{% if request.user.is_authenticated %}

<div style="background:#606060; padding-top:1px; padding-bottom:1px;">
	<div id="inline_navbar" >
		<span id="inline_username">Hello, {{request.user}}</span>
		<span class="inline_space"> </span>
		<a class="inline_user_action" href='/'>Home</a>
		<a class="inline_user_action" href="javascript:mainLayout.toggle('south')">Chat</a>
		<a class="inline_user_action" href='{% url "posts:new" %}'>Write Post</a>
		<a class="inline_user_action" href='{% url "posts:new" %}?game=yes'>Submit Game</a>
		<a class="inline_user_action" href='{% url "posts:new" %}?image=yes'>Submit Image</a>
		<span class="inline_space"> </span>
		<a class="inline_user_action" href='{% url "users:edit_profile" %}'>Edit Profile</a>
		<a class="inline_user_action" href='{% url "users:logout" %}'>Log Out</a>
		<span class="inline_space"> </span>
	</div>
</div>

{% else %}

<div style="background:#606060; padding-top:1px; padding-bottom:1px;">
	<div id="inline_navbar" >
		<span id="inline_username">Hello, {{request.user}}</span>
		<span class="inline_space"> </span>
		<a class="inline_user_action" href='/'>Home</a>
		<a class="inline_user_action" href='{% url "users:register" %}'>Register</a>
		<a class="inline_user_action" href='{% url "users:login" %}'>Login</a>
		<span class="inline_space"> </span>
	</div>
</div>

{% endif %}

templates/default/users/login.html
{% extends "base.html" %}
{% load url from future %}
{% block content %}
<h2>User Login</h2>
<small>Please login with your old GDI account if you have one</small>
<form method='post' action='{% url "users:login" %}'>
{{form.errors}}
{{form.as_p}}
{% csrf_token %}
<button type='submit'>Login</button>
</form>
{% endblock %}

templates/default/users/login_widget.html
{% load url from future %}

{% if request.user.is_authenticated %}
{% else %}

<div style="text-align: center;">
	<form method='post' action='{% url "users:login" %}'>
	<div style="display: inline-block; text-align:center; margin-right:1px;">
		<small>username</small>
		<br>
		<input class="normal_input" name="username" id="username" style="width: 80px;" type="text">
	</div>
	<div style="display: inline-block; text-align:center; margin-right:1px;">
		<small>password</small>
		<br>
		<input class="normal_input" name="password" id="password" style="width: 80px;" type="password">
	</div>
	<div style="display: inline-block; vertical-align:bottom; margin-bottom:2px;">
		<button class="normal_button" type="submit">Login</button>
	</div>
	<br>
	<small style="text-align: left;">Please login with your old GDI account<br>if you have one
	</small>
	{% csrf_token %}
	</form>
</div>

{% endif %}

templates/default/users/register.html
{% extends "base.html" %}
{% load url from future %}
{% block content %}
<h2>User Registration</h2>
<form method='post' action='{% url "users:register" %}'>
{{form.errors}}
{{form.as_p}}
{% csrf_token %}
<button type='submit'>register</button>
</form>
{% endblock %}